# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GimmeSnowflakeCreds < Formula
  desc "Okta > OAuth > Snowflake > Creds"
  homepage "https://github.com/hginsights/gimme-snowflake-creds"
  version "0.2.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HGInsights/gimme-snowflake-creds/releases/download/0.2.3/gimme-snowflake-creds_0.2.3_darwin_amd64.tar.gz"
      sha256 "e251ff854b56e7670ff5e90a47f9be7e97a06a162a6a47e2a1fec448a7a9f305"
    end
    if Hardware::CPU.arm?
      url "https://github.com/HGInsights/gimme-snowflake-creds/releases/download/0.2.3/gimme-snowflake-creds_0.2.3_darwin_arm64.tar.gz"
      sha256 "3ef27d9d864c55cc79e57ff45c5db55786fe7d8c6e81439137e6f2b878692b59"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/HGInsights/gimme-snowflake-creds/releases/download/0.2.3/gimme-snowflake-creds_0.2.3_linux_amd64.tar.gz"
      sha256 "1714d4a9cd9889d0476738c77a62f3db41ca6b3d512ae3f0044568b99838265d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HGInsights/gimme-snowflake-creds/releases/download/0.2.3/gimme-snowflake-creds_0.2.3_linux_arm64.tar.gz"
      sha256 "d536574e906bde53b3d37ad655e7568f77a9406739bcb809bfe8392e4c6c3e6f"
    end
  end

  def install
    bin.install "gimme-snowflake-creds"
  end
end
