# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy.rb"
class GimmeSnowflakeCreds < Formula
  desc "Okta > OAuth > Snowflake > Creds"
  homepage "https://github.com/hginsights/gimme-snowflake-creds"
  version "0.3.6"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/HGInsights/gimme-snowflake-creds/releases/download/0.3.6/gimme-snowflake-creds_0.3.6_darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d8efe99360c1cc97ef959223df67f0240427fba8cb58055178b77fecc9a3fc76"
    end
    if Hardware::CPU.intel?
      url "https://github.com/HGInsights/gimme-snowflake-creds/releases/download/0.3.6/gimme-snowflake-creds_0.3.6_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2bbe41ddb1b73059a5ff3a46c962d575203321d2b0ce0111399d886068b45460"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HGInsights/gimme-snowflake-creds/releases/download/0.3.6/gimme-snowflake-creds_0.3.6_linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "582e9a9d4da190ef96a6b41bfa7aa8f30fca5b6d81813f40cd76f42d66eab4a1"
    end
    if Hardware::CPU.intel?
      url "https://github.com/HGInsights/gimme-snowflake-creds/releases/download/0.3.6/gimme-snowflake-creds_0.3.6_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3bebf41a07f51c3d5e70d1b001bc0309569070a749b9460ea4b70b477675a139"
    end
  end

  def install
    bin.install "gimme-snowflake-creds"
  end
end
