# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GimmeSnowflakeCreds < Formula
  desc "Okta > OAuth > Snowflake > Creds"
  homepage "https://github.com/hginsights/gimme-snowflake-creds"
  version "0.6.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/HGInsights/gimme-snowflake-creds/releases/download/0.6.3/gimme-snowflake-creds_0.6.3_darwin_arm64.tar.gz"
      sha256 "15f112bd75f9b29fd102608f7fc50d7543a9a7fd78a230e177401369d7eb919c"

      def install
        bin.install "gimme-snowflake-creds"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HGInsights/gimme-snowflake-creds/releases/download/0.6.3/gimme-snowflake-creds_0.6.3_darwin_amd64.tar.gz"
      sha256 "fd05f132cb7f63ebe81afa71cb7a1bec6e8e59eea487861ec113e303f65961ad"

      def install
        bin.install "gimme-snowflake-creds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HGInsights/gimme-snowflake-creds/releases/download/0.6.3/gimme-snowflake-creds_0.6.3_linux_arm64.tar.gz"
      sha256 "d7b05307fd29f1e914f4921115ddee73b77fc703d7377a1cd6d587911f83a6f7"

      def install
        bin.install "gimme-snowflake-creds"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/HGInsights/gimme-snowflake-creds/releases/download/0.6.3/gimme-snowflake-creds_0.6.3_linux_amd64.tar.gz"
      sha256 "ba0218dec615eea473404dc8bd6abe2a97dcafe5ccea61df05a49d805056f5b1"

      def install
        bin.install "gimme-snowflake-creds"
      end
    end
  end
end
